---
title: "Distributional consequences of climate policy"
author: "Sophia Leiker"
date: "5/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(broom)
library(janitor)
library(rootSolve)
```

```{r}
#Reading in the data

df <- read_csv(here("data", "HW3_data.csv")) %>% 
  select(-1) %>% 
  clean_names()
```

Functions
```{r}
model_demand_l <- lm(price_cents  ~ q_low_kwh, data=df)
model_demand_h <- lm(price_cents ~ q_high_kwh, data=df)
```

# need to rearrange the parameter to get Q(P)! 

# Qgg = Qlow(P) + Qlow(h) 

# Importantly, since they-intercepts are different, we know that Qagg(P) will have a kink. I include an ifelse() statement to take
# care of the kink.

```{r}
# define a function to get demand

demand <- function(p, model){
  q <- (p - model$coefficients[[1]])/model$coefficients[[2]]
  q <- ifelse(q<0,0,q)
  return(q)
}
```


```{r}
# for each p level, return estimated aggregate demand
demand_agg <- function(p){
  q <- demand(p, model_demand_l) + demand(p, model_demand_h)
  return(q)
}

demand_agg2 <- function(p){
  q <- demand(p, model_demand_l) + demand(p, model_demand_h2)
  return(q)
}
```

```{r}
price = seq(0, 30, length.out = 100)
Qagg <- map(price, demand_agg) %>% unlist()


demand_agg2 <- function(p){
  q <- demand(p, model_demand_l) + demand(p, model_demand_h2)
  return(q)
}

df5 <- df %>% 
  mutate(price_cents = price_cents * 0.5)

model_demand_h2 <- lm(price_cents ~ q_high_kwh, data=df)

Qagg2 <- map(price, demand_agg) %>% unlist()



```

```{r}
df<- tibble(Qagg = Qagg, price = price)
```

```{r}
ggplot(df, aes(Qagg, price)) +
  geom_line() +
  labs(title = "Demand Curves") +
  geom_line(data = demand_table, aes(x = demand_low, y = price_cents)) +
  geom_line(data = demand_table, aes(x = demand_high, y = price_cents)) +
  scale_x_continuous(limits = c(0, 9e+05))

ggplot(data = demand_table, aes(x = demand_low, y = price_cents)) +
  geom_point() +
  labs(title = "Demand Low")

ggplot(data = demand_table, aes(x = demand_high, y = price_cents)) +
  geom_point() +
    labs(title = "Demand High")
```

```{r}
#updating data frame to get supply curve

slope_supply <- 10/536719.47

df2 <- df %>% 
  mutate("supply" = (Qagg * slope_supply)) %>% 
  mutate("MEC" = 2)

ggplot(df, aes(Qagg, price)) +
  geom_line(color = "forestgreen") +
  labs(title = "Supply and Demand Curves", y = "Price (cents)", x = "Electricity Quantity (kWh)") +
  geom_line(data = demand_table, aes(x = demand_low, y = price_cents), color = "blue", linetype = "dashed") +
  geom_line(data = demand_table, aes(x = demand_high, y = price_cents), color = "purple", linetype = "dashed") +
  scale_x_continuous(limits = c(0, 9e+05)) +
  geom_line(data = df2, aes(x = Qagg, y = supply), color = "orange") +
  geom_line(data = df2, aes(x = Qagg, y = MEC), color = "red")

```

```{r}
# I also define functions for calculating the consumer surplus:

CS <- function(p, model){
  q <- demand(p, model)
  cs <- 0.5*(model$coefficients[[1]] - p)*q
  return(cs)
}

CS_agg <- function(p){
  cs <- CS(p,model_demand_l) + CS(p,model_demand_h)
  return(cs)
}
```

```{r}
#Finding the consumer surplus at price 10

CS(10, model_demand_l)

CS(10, model_demand_h)

CS_agg(10)

#difference in consumer surplus between the high and low groups 
consumer_surplus_diff <- CS(10, model_demand_h) - CS(10, model_demand_l)
consumer_surplus_diff

```

```{r}
#QUESTION 6
#updating data to get the new high demand curve 

df3 <- df %>% 
  mutate("supply" = (Qagg * slope_supply)) %>% 
  mutate("MEC" = 2)

ggplot(df, aes(Qagg, price)) +
  geom_line(color = "forestgreen") +
  labs(title = "Supply and Demand Curves", y = "Price (cents)", x = "Electricity Quantity (kWh)") +
  geom_line(data = demand_table, aes(x = demand_low, y = price_cents), color = "blue", linetype = "dashed") +
  geom_line(data = demand_table, aes(x = demand_high, y = price_cents), color = "purple", linetype = "dashed") +
  scale_x_continuous(limits = c(0, 9e+05)) +
  geom_line(data = df2, aes(x = Qagg, y = supply), color = "orange") +
  geom_line(data = df2, aes(x = Qagg, y = MEC), color = "red")

```
```


